import React, { useState, useEffect } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { X, ChevronLeft, ChevronRight, Star, Heart, Bookmark, Share2, MapPin } from 'lucide-react';
import ReviewModal, { type ReviewPayload } from './ReviewModal';
import { recommendationsApi, type PlaceRecommendation } from '../services/recommendations';
import { formatGoogleTypeForDisplay } from '../utils/placeTypes';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { Avatar, AvatarImage, AvatarFallback } from '@/components/ui/avatar';
import { Separator } from '@/components/ui/separator';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import './ContentCard.css';

export interface PlaceDetails {
  id: string;
  name: string;
  address: string;
  category: string; // Google Places type (e.g., 'restaurant', 'bar', 'cafe', 'night_club', etc.)
  placeType?: string; // Google Places type for backward compatibility
  userRating?: number;
  friendsRating?: number;
  personalReview?: string;
  images?: string[];
  isLiked?: boolean;
  isSaved?: boolean;
  latitude?: number;
  longitude?: number;
  google_place_id?: string;
}

// Real review type from API
interface RealReview {
  id: number;
  user_name: string;
  title?: string;
  notes?: string;
  rating?: number;
  visit_date?: string;
  created_at: string;
}

interface ContentCardProps {
  place: PlaceDetails;
  onClose: () => void;
  onRate: (rating: number) => void;
  onLike: () => void;
  onSave: () => void;
  onShare: () => void;
}

// Helper functions
const formatDate = (dateString: string): string => {
  const date = new Date(dateString);
  const now = new Date();
  const diffTime = Math.abs(now.getTime() - date.getTime());
  const diffDays = Math.ceil(diffTime / (1000 * 60 * 60 * 24));
  
  if (diffDays === 1) return '1d ago';
  if (diffDays < 7) return `${diffDays}d ago`;
  if (diffDays < 30) return `${Math.floor(diffDays / 7)}w ago`;
  if (diffDays < 365) return `${Math.floor(diffDays / 30)}mo ago`;
  return `${Math.floor(diffDays / 365)}y ago`;
};

const getDisplayTitle = (title: string | undefined, placeName: string): string | undefined => {
  if (!title) return undefined;
  const autoGeneratedPattern = new RegExp(`^Review of ${placeName}$`, 'i');
  return autoGeneratedPattern.test(title) ? undefined : title;
};

const getInitials = (name: string): string => 
  name.split(' ')
    .map(n => n[0])
    .join('')
    .toUpperCase()
    .slice(0, 2);

const ContentCard: React.FC<ContentCardProps> = ({
  place,
  onClose,
  onRate,
  onLike,
  onSave,
  onShare,
}) => {
  const [currentImageIndex, setCurrentImageIndex] = useState(0);
  const [userRating, setUserRating] = useState(place.userRating || 0);
  const [realReviews, setRealReviews] = useState<RealReview[]>([]);
  const [reviewsLoading, setReviewsLoading] = useState(true);
  const [reviewsError, setReviewsError] = useState<string | null>(null);
  const [reviewOpen, setReviewOpen] = useState(false);

  // Fetch real recommendations when component mounts
  useEffect(() => {
    const fetchReviews = async () => {
      if (!place.google_place_id) {
        setReviewsLoading(false);
        setReviewsError('No Google Place ID available');
        return;
      }

      try {
        setReviewsLoading(true);
        setReviewsError(null);
        
        // First, get the database place ID from Google Place ID
        const placeInfo = await recommendationsApi.getPlaceByGoogleId(place.google_place_id);
        
        if (!placeInfo) {
          // Place doesn't exist in our database yet, so no reviews
          setRealReviews([]);
          setReviewsLoading(false);
          return;
        }

        // Now get recommendations using the database place ID
        const recommendations = await recommendationsApi.getPlaceRecommendations(placeInfo.id, 'all', 10);
        
        // Transform API data to our review format
        const reviews: RealReview[] = recommendations.map(rec => ({
          id: rec.id,
          user_name: rec.user_name,
          title: rec.title,
          notes: rec.notes,
          rating: rec.rating,
          visit_date: rec.visit_date,
          created_at: rec.created_at
        }));

        setRealReviews(reviews);
      } catch (error) {
        console.error('Failed to fetch reviews:', error);
        setReviewsError(error instanceof Error ? error.message : 'Failed to load reviews');
      } finally {
        setReviewsLoading(false);
      }
    };

    fetchReviews();
  }, [place.google_place_id]);

  const handleRate = (rating: number) => {
    setUserRating(rating);
    onRate(rating);
  };

  const totalImages = place.images?.length || 0;

  const handleSubmitReview = (payload: ReviewPayload) => {
    console.log('Review submitted:', payload);
    // This is now handled by the ReviewModal internally
  };

  const handleReviewSuccess = (result: { place_id: number; annotation_id: number }) => {
    console.log('Review saved successfully:', result);
    // Refresh reviews after successful submission by refetching
    const fetchReviews = async () => {
      if (!place.google_place_id) return;
      
      try {
        const placeInfo = await recommendationsApi.getPlaceByGoogleId(place.google_place_id);
        if (!placeInfo) return;

        const recommendations = await recommendationsApi.getPlaceRecommendations(placeInfo.id, 'all', 10);
        
        const reviews: RealReview[] = recommendations.map(rec => ({
          id: rec.id,
          user_name: rec.user_name,
          title: rec.title,
          notes: rec.notes,
          rating: rec.rating,
          visit_date: rec.visit_date,
          created_at: rec.created_at
        }));

        setRealReviews(reviews);
      } catch (error) {
        console.error('Failed to refresh reviews:', error);
      }
    };
    
    fetchReviews();
  };

  const handleReviewError = (error: string) => {
    console.error('Review save failed:', error);
    // You can add UI feedback here, like showing an error toast
  };

  // Calculate average rating from real reviews
  const calculateAverageRating = () => {
    if (realReviews.length === 0) return 0;
    const totalRating = realReviews.reduce((sum, review) => sum + (review.rating || 0), 0);
    return totalRating / realReviews.length;
  };

  const actualAverageRating = calculateAverageRating();

  // Render components
  const renderImageGallery = () => (
    <div className="relative w-full h-72 overflow-hidden">
      {place.images && place.images.length > 0 ? (
        <>
          <img 
            src={place.images[currentImageIndex]} 
            alt={place.name}
            className="w-full h-full object-cover"
          />
          
          {/* Close Button */}
          <Button
            variant="secondary"
            size="icon"
            onClick={onClose}
            className="absolute top-4 right-4 h-10 w-10 rounded-full bg-black/60 text-white hover:bg-black/80 backdrop-blur-sm border-0"
          >
            <X className="h-5 w-5" />
          </Button>
          
          {/* Navigation Arrows */}
          {totalImages > 1 && (
            <>
              <Button
                variant="secondary"
                size="icon"
                onClick={() => setCurrentImageIndex((prev) => (prev - 1 + totalImages) % totalImages)}
                className="absolute left-4 top-1/2 -translate-y-1/2 h-10 w-10 rounded-full bg-black/60 text-white hover:bg-black/80 backdrop-blur-sm border-0"
              >
                <ChevronLeft className="h-5 w-5" />
              </Button>
              <Button
                variant="secondary"
                size="icon"
                onClick={() => setCurrentImageIndex((prev) => (prev + 1) % totalImages)}
                className="absolute right-4 top-1/2 -translate-y-1/2 h-10 w-10 rounded-full bg-black/60 text-white hover:bg-black/80 backdrop-blur-sm border-0"
              >
                <ChevronRight className="h-5 w-5" />
              </Button>
              
              {/* Image Indicators */}
              <div className="absolute bottom-4 left-1/2 -translate-x-1/2 flex gap-2">
                {place.images.map((_, index) => (
                  <button
                    key={index}
                    className={`h-2 w-2 rounded-full transition-all duration-200 ${
                      index === currentImageIndex 
                        ? 'bg-white scale-110' 
                        : 'bg-white/60 hover:bg-white/80'
                    }`}
                    onClick={() => setCurrentImageIndex(index)}
                    aria-label={`Go to image ${index + 1}`}
                  />
                ))}
              </div>
            </>
          )}
        </>
      ) : (
        <div className="w-full h-full bg-gradient-to-br from-gray-50 to-gray-100 flex items-center justify-center">
          <div className="text-center">
            <div className="text-6xl mb-4 opacity-30">📷</div>
            <p className="text-gray-500 font-medium">No image available</p>
          </div>
          
          {/* Close Button */}
          <Button
            variant="secondary"
            size="icon"
            onClick={onClose}
            className="absolute top-4 right-4 h-10 w-10 rounded-full bg-black/60 text-white hover:bg-black/80 backdrop-blur-sm border-0"
          >
            <X className="h-5 w-5" />
          </Button>
        </div>
      )}
    </div>
  );

  const renderPlaceHeader = () => (
    <div className="space-y-3">
      <CardTitle className="text-2xl font-bold tracking-tight text-gray-900">
        {place.name}
      </CardTitle>
      <div className="flex items-start gap-2 text-sm text-gray-600">
        <MapPin className="h-4 w-4 mt-0.5 flex-shrink-0" />
        <span className="leading-relaxed">{place.address}</span>
      </div>
      {place.category && place.category !== 'point_of_interest' && (
        <Badge variant="secondary" className="w-fit bg-gray-100 text-gray-700 border-gray-200 font-medium">
          {formatGoogleTypeForDisplay(place.category)}
        </Badge>
      )}
    </div>
  );

  const renderReviewItem = (review: RealReview, index: number) => (
    <motion.div
      key={review.id}
      className="group flex gap-3 p-3 rounded-lg hover:bg-gray-50/50 transition-all duration-200 border border-transparent hover:border-gray-100"
      initial={{ opacity: 0, y: 10 }}
      animate={{ opacity: 1, y: 0 }}
      exit={{ opacity: 0, y: -10 }}
      transition={{ 
        delay: index * 0.05,
        duration: 0.2,
        ease: 'easeOut'
      }}
    >
      <Avatar className="h-8 w-8 ring-1 ring-gray-100">
        <AvatarFallback className="text-xs font-semibold bg-gradient-to-br from-blue-500 to-purple-600 text-white">
          {getInitials(review.user_name)}
        </AvatarFallback>
      </Avatar>
      
      <div className="flex-1 min-w-0 space-y-2">
        <div className="flex items-center gap-2 flex-wrap">
          <span className="font-semibold text-gray-900 text-sm">{review.user_name}</span>
          <span className="text-gray-400">•</span>
          <span className="text-gray-500 text-xs">
            {formatDate(review.created_at)}
          </span>
          {review.rating && (
            <>
              <span className="text-gray-400">•</span>
              <div className="flex items-center gap-1">
                {Array.from({ length: review.rating }).map((_, i) => (
                  <Star key={i} className="h-3 w-3 fill-yellow-400 text-yellow-400" />
                ))}
              </div>
            </>
          )}
        </div>
        
        {(getDisplayTitle(review.title, place.name) || review.notes) && (
          <div className="space-y-1">
            {getDisplayTitle(review.title, place.name) && (
              <p className="font-medium text-gray-900 text-sm">
                {getDisplayTitle(review.title, place.name)}
              </p>
            )}
            {review.notes && (
              <p className="text-gray-600 text-sm leading-relaxed">{review.notes}</p>
            )}
          </div>
        )}
        
        {/* Review Actions */}
        <div className="flex items-center gap-3 pt-1">
          <button 
            className="flex items-center gap-1.5 text-gray-500 hover:text-red-500 transition-colors duration-200 text-xs font-medium"
            onClick={() => console.log('Like review:', review.id)}
          >
            <Heart className="h-3.5 w-3.5" />
            <span>Like</span>
          </button>
          
          <button 
            className="flex items-center gap-1.5 text-gray-500 hover:text-blue-500 transition-colors duration-200 text-xs font-medium"
            onClick={() => console.log('Reply to review:', review.id)}
          >
            <svg className="h-3.5 w-3.5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M3 10h10a8 8 0 018 8v2M3 10l6 6m-6-6l6-6" />
            </svg>
            <span>Reply</span>
          </button>
        </div>
      </div>
    </motion.div>
  );

  const renderReviewsSection = () => (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <h3 className="text-lg font-semibold text-gray-900">Reviews ({realReviews.length})</h3>
        <button 
          className="write-review-btn"
          onClick={() => setReviewOpen(true)}
        >
          Write a review
        </button>
      </div>
      
      <div className="space-y-3">
        {reviewsLoading ? (
          <div className="p-8 text-center">
            <div className="animate-spin rounded-full h-8 w-8 border-b-2 border-gray-900 mx-auto mb-3"></div>
            <p className="text-gray-500 font-medium">Loading reviews...</p>
          </div>
        ) : reviewsError ? (
          <div className="p-6 text-center rounded-xl bg-red-50 border border-red-100">
            <p className="text-red-600 font-medium">
              Error loading reviews: {reviewsError}
            </p>
          </div>
        ) : realReviews.length === 0 ? (
          <div className="p-8 text-center rounded-xl bg-gray-50 border border-gray-100">
            <div className="text-4xl mb-3 opacity-30">💬</div>
            <p className="text-gray-600 font-medium mb-2">No reviews yet</p>
            <p className="text-gray-500 text-sm">Be the first to review this place!</p>
          </div>
        ) : (
          <AnimatePresence>
            {realReviews.map((review, index) => renderReviewItem(review, index))}
          </AnimatePresence>
        )}
      </div>
    </div>
  );

  const renderPersonalReview = () => (
    place.personalReview && (
      <div className="flex gap-4 p-4 rounded-xl bg-blue-50/50 border border-blue-100">
        <Avatar className="h-10 w-10 ring-2 ring-blue-100">
          <AvatarFallback className="text-sm font-semibold bg-gradient-to-br from-blue-600 to-indigo-600 text-white">
            You
          </AvatarFallback>
        </Avatar>
        
        <div className="flex-1 space-y-2">
          <div className="flex items-center gap-2">
            <span className="font-semibold text-gray-900 text-sm">Your Review</span>
            <span className="text-gray-400">•</span>
            <span className="text-gray-500 text-sm">Personal notes</span>
          </div>
          <p className="text-gray-700 text-sm leading-relaxed">{place.personalReview}</p>
        </div>
      </div>
    )
  );

  const renderSocialActions = () => (
    <div className="flex gap-3 pt-6">
      
      <Button 
        variant={place.isSaved ? "default" : "outline"}
        size="sm"
        onClick={onSave}
        className={`flex-1 font-medium ${
          place.isSaved 
            ? "bg-blue-500 hover:bg-blue-600 text-white border-blue-500" 
            : "text-gray-700 border-gray-200 hover:bg-gray-50 hover:border-gray-300"
        }`}
      >
        <Bookmark className={`h-4 w-4 ${place.isSaved ? 'fill-current' : ''}`} />
        {place.isSaved ? 'Saved' : 'Save'}
      </Button>
      
      <Button 
        variant="outline"
        size="sm"
        onClick={onShare}
        className="flex-1 font-medium text-gray-700 border-gray-200 hover:bg-gray-50 hover:border-gray-300"
      >
        <Share2 className="h-4 w-4" />
        Share
      </Button>
    </div>
  );

  return (
    <motion.div
      className="fixed inset-y-0 left-0 w-96 bg-white border-r border-gray-200 shadow-2xl z-50 overflow-y-auto pt-16"
      initial={{ x: '-100%' }}
      animate={{ x: 0 }}
      exit={{ x: '-100%' }}
      transition={{ duration: 0.3, ease: 'easeOut' }}
    >
      {renderImageGallery()}
      
      <div className="p-6 space-y-8">
        {renderPlaceHeader()}
        
        <Separator className="bg-gray-100" />
        
        {renderReviewsSection()}
        
        {renderPersonalReview()}
        
        {renderSocialActions()}
      </div>

      {/* Review Modal */}
      <ReviewModal 
        isOpen={reviewOpen} 
        onClose={() => setReviewOpen(false)} 
        onSubmit={handleSubmitReview}
        placeData={{
          name: place.name,
          address: place.address,
          latitude: place.latitude,
          longitude: place.longitude,
          google_place_id: place.google_place_id,
        }}
        onSuccess={handleReviewSuccess}
        onError={handleReviewError}
      />
    </motion.div>
  );
};

export default ContentCard; 